/* eslint-disable import/no-unresolved */
/* eslint-disable import/extensions */
import type { NextPage } from 'next';
import Head from 'next/head';
import ButtonComponent from '../components/button/button';
// import LoginForm from '../modules/login/loginForm';
import styles from '../styles/Home.module.css';
// import { io } from "socket.io-client";

function accessProtectedRoute(token: string) {
  const accessToken = 'Bearer '.concat(token);
  fetch('http://localhost:3001/profile', {
    headers: {
      Authorization: accessToken,
    },
  })
    .then((res) => res.json())
    .then((data) => console.log(data))
    .catch((err) => console.log(err));
}

function login() {
  const user = {
    username: 'ivan',
    password: '1234',
  };
  fetch('http://localhost:3001/login', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(user),
  })
    .then((res) => res.json())
    .then((data) => {
      console.log(data);
      accessProtectedRoute(data.access_token);
    })
    .catch((err) => {
      console.log(err);
    });
}

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    {/* <LoginForm /> */}
    <ButtonComponent title='login' onClick={login}></ButtonComponent>
  </div>
);

// const socket = io('http://localhost:3001');
// socket.emit("msgToServer", "hi from client");
// socket.on("connect", () => {
//   console.log("Connected with server : ", socket.connected);
// });

// socket.on("numberToClient", (data) => { //from server
//   console.log(data);
// });

export default Home;
