export const jwtConstants = {
  SECRET_ACCESS_TOKEN_KEY: 'qI7jtdTStMT0sGZyJxsdMyhThZMQmxrGlLS2JwT684s=',
  SECRET_ACCESS_EXPIRED_TIME: '5m',
  SECRET_REFRESH_TOKEN_KEY: 'aa1jtdTSteW0sGOLPsdMdyhThZMQmxrGlLS2JwT123a=',
  SECRET_REFRESH_EXPIRED_TIME: '7d',
};
